{
 "title": "GLOBEX Sentiment Analysis Dashboard",
 "description": "GLOBEX Sentiment Analysis Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "GLOBEX Customer Sentiments",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "category = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"category\" and r[\"_value\"] == \"clothing\")\n\npositive_count = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"response\" and r[\"_value\"] == \"positive\")\n  |> count()\n  |> map(fn: (r) => ({r with response_name: \"positive_count\"}))\n\nneutral_count = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"response\" and r[\"_value\"] == \"neutral\")\n  |> count()\n  |> map(fn: (r) => ({r with response_name: \"neutral_count\"}))\n\nnegative_count = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"response\" and r[\"_value\"] == \"negative\")\n  |> count()\n  |> map(fn: (r) => ({r with response_name: \"negative_count\"}))\n\ncategory |> yield(name: \"category\")\npositive_count |> yield(name: \"positive_count\")\nneutral_count |> yield(name: \"neutral_count\")\nnegative_count |> yield(name: \"negative_count\")"
    }
   ]
  },
  {
   "title": "Clothing Category Real Time Sentiment Analysis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "categorys = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"category\" and r[\"_value\"] == \"clothing\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nproductIDs = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"product_id\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nscores = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"score\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\njoin(\n  tables: {categorys: categorys, scores: scores},\n  on: [\"_time\"]\n)\n|> yield(name: \"joined_data\")"
    }
   ]
  },
  {
   "title": "Category Clothing Sentiment View",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 8 },
   "targets": [
    {
     "query": "categorys = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"category\" and r[\"_value\"] == \"clothing\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nproductIDs = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"product_id\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nscores = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"score\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\njoin(\n  tables: {categorys: categorys, scores: scores},\n  on: [\"_time\"]\n)\n|> yield(name: \"joined_data\")"
    }
   ]
  },
  {
   "title": "Last Sentiment for Clothing Category",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "categorys = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"category\" and r[\"_value\"] == \"clothing\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nproductIDs = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"product_id\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nscores = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"score\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\njoin(\n  tables: {categorys: categorys, scores: scores},\n  on: [\"_time\"]\n)\n|> yield(name: \"joined_data\")"
    }
   ]
  },
  {
   "title": "Category Bags Sentiment View",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 14 },
   "targets": [
    {
     "query": "categorys = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"category\" and r[\"_value\"] == \"bags\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nproductIDs = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"product_id\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nscores = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"score\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\njoin(\n  tables: {categorys: categorys, scores: scores},\n  on: [\"_time\"]\n)\n|> yield(name: \"joined_data\")"
    }
   ]
  },
  {
   "title": "Last Sentiment for Bags Category",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "categorys = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"category\" and r[\"_value\"] == \"bags\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nproductIDs = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"product_id\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nscores = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"score\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\njoin(\n  tables: {categorys: categorys, scores: scores},\n  on: [\"_time\"]\n)\n|> yield(name: \"joined_data\")"
    }
   ]
  },
  {
   "title": "Bags Category Real Time Sentiment Analysis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "categorys = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"category\" and r[\"_value\"] == \"bags\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nproductIDs = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"product_id\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nscores = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"score\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\njoin(\n  tables: {categorys: categorys, scores: scores},\n  on: [\"_time\"]\n)\n|> yield(name: \"joined_data\")"
    }
   ]
  },
  {
   "title": "Clothing Tabular Data",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 21 },
   "targets": [
    {
     "query": "categorys = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"category\" and r[\"_value\"] == \"clothing\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nproductIDs = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"product_id\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nscores = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"score\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\njoin(\n  tables: {categorys: categorys, scores: scores},\n  on: [\"_time\"]\n)\n|> yield(name: \"joined_data\")"
    }
   ]
  },
  {
   "title": "Bags Tabular Data",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 21 },
   "targets": [
    {
     "query": "categorys = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"category\" and r[\"_value\"] == \"bags\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nproductIDs = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"product_id\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\nscores = from(bucket: \"globex-bucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"globex-bucket\" and r[\"_field\"] == \"score\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_measurement\"], valueColumn:\"_value\")\n\njoin(\n  tables: {categorys: categorys, scores: scores},\n  on: [\"_time\"]\n)\n|> yield(name: \"joined_data\")"
    }
   ]
  }
 ]
}